-- ============================================================
-- App ATS - SST | GIGA
-- Migración SQLite -> Supabase/PostgreSQL
-- Generado a partir de: ats_app.db
-- Fecha de generación: 2026-05-19 14:18:24
--
-- Qué incluye:
--   1. Estructura completa de tablas para Supabase/PostgreSQL.
--   2. Relaciones, constraints, índices, vistas y triggers updated_at.
--   3. Datos seed de tablas catálogo.
--   4. Datos del catálogo maestro trabajador.
--
-- Qué NO incluye:
--   - Registros transaccionales de ATS.
--   - Registros de usuario con password_hash.
--
-- Nota sobre usuarios:
--   Este script está pensado para usar Supabase Auth como fuente de autenticación.
--   La tabla public.usuario funciona como perfil interno de la app y mapa de roles.
--   Cada usuario autenticado en auth.users puede tener un perfil en public.usuario.
--
-- Recomendación:
--   Ejecutar primero en un proyecto Supabase nuevo o en una rama/staging.
-- ============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- Limpieza controlada de objetos de la app
-- ADVERTENCIA: esto elimina tablas/vistas existentes de la app ATS.
-- Usar solo en una base nueva o entorno staging.
-- ============================================================

DROP VIEW IF EXISTS public.vw_ats_paso_peligro_control CASCADE;
DROP VIEW IF EXISTS public.vw_ats_trabajador_snapshot CASCADE;
DROP VIEW IF EXISTS public.vw_ats_resumen CASCADE;
DROP VIEW IF EXISTS public.vw_ats_metrica_por_peligro CASCADE;
DROP VIEW IF EXISTS public.vw_ats_metrica_por_estado CASCADE;

DROP TABLE IF EXISTS public.ats_paso_peligro_control CASCADE;
DROP TABLE IF EXISTS public.ats_paso_peligro CASCADE;
DROP TABLE IF EXISTS public.ats_paso CASCADE;
DROP TABLE IF EXISTS public.ats_peligro CASCADE;
DROP TABLE IF EXISTS public.ats_firma_final CASCADE;
DROP TABLE IF EXISTS public.ats_trabajador CASCADE;
DROP TABLE IF EXISTS public.ats_documento CASCADE;
DROP TABLE IF EXISTS public.ats_certificado CASCADE;
DROP TABLE IF EXISTS public.ats_apoyo CASCADE;
DROP TABLE IF EXISTS public.ats CASCADE;
DROP TABLE IF EXISTS public.usuario CASCADE;
DROP TABLE IF EXISTS public.trabajador CASCADE;
DROP TABLE IF EXISTS public.firma_tipo_catalogo CASCADE;
DROP TABLE IF EXISTS public.control_catalogo CASCADE;
DROP TABLE IF EXISTS public.peligro_catalogo CASCADE;
DROP TABLE IF EXISTS public.certificado_catalogo CASCADE;
DROP TABLE IF EXISTS public.apoyo_catalogo CASCADE;
DROP TABLE IF EXISTS public.ats_tipo CASCADE;
DROP TABLE IF EXISTS public.ats_estado CASCADE;
DROP TABLE IF EXISTS public.rol CASCADE;

DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE;

-- ============================================================
-- Función genérica para updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Catálogos y perfiles de usuario
-- ============================================================

CREATE TABLE public.rol (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación opcional con Supabase Auth.
    -- Se llena cuando el usuario ya existe en auth.users.
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,

    rol_id INTEGER NOT NULL REFERENCES public.rol(id),
    uuid TEXT NOT NULL DEFAULT replace(gen_random_uuid()::TEXT, '-', '') UNIQUE,
    nombre_completo TEXT NOT NULL,
    email TEXT UNIQUE,
    username TEXT NOT NULL UNIQUE,

    -- Campo de transición. No se recomienda usarlo si se adopta Supabase Auth.
    -- Se deja nullable para no obligar a guardar contraseñas en public.usuario.
    password_hash TEXT,

    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_usuario_rol ON public.usuario(rol_id);
CREATE INDEX idx_usuario_auth_user_id ON public.usuario(auth_user_id);

CREATE TABLE public.ats_estado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.ats_tipo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.apoyo_catalogo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    permite_descripcion_libre BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.certificado_catalogo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    permite_descripcion_libre BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.firma_tipo_catalogo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.peligro_catalogo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    numero_visual INTEGER NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    permite_descripcion_libre BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.control_catalogo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    tipo_control TEXT,
    permite_descripcion_libre BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL DEFAULT 1,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_control_catalogo_activo ON public.control_catalogo(activo);
CREATE INDEX idx_control_catalogo_tipo ON public.control_catalogo(tipo_control);

CREATE TABLE public.trabajador (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid TEXT NOT NULL DEFAULT replace(gen_random_uuid()::TEXT, '-', '') UNIQUE,
    numero_documento TEXT NOT NULL UNIQUE,
    nombre_completo TEXT NOT NULL,
    cargo TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trabajador_activo ON public.trabajador(activo);
CREATE INDEX idx_trabajador_nombre ON public.trabajador(nombre_completo);

-- ============================================================
-- Tablas transaccionales ATS
-- ============================================================

CREATE TABLE public.ats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid TEXT NOT NULL DEFAULT replace(gen_random_uuid()::TEXT, '-', '') UNIQUE,
    codigo_publico TEXT NOT NULL UNIQUE,

    estado_id INTEGER NOT NULL REFERENCES public.ats_estado(id),
    tipo_ats_id INTEGER NOT NULL REFERENCES public.ats_tipo(id),
    creado_por_usuario_id INTEGER NOT NULL REFERENCES public.usuario(id),

    empresa_persona_ejecuta TEXT NOT NULL,
    fecha_elaboracion DATE NOT NULL,
    ciudad TEXT NOT NULL,
    area_lugar TEXT NOT NULL,
    numero_ats TEXT,
    duracion_actividad TEXT NOT NULL,
    actividad_alto_riesgo BOOLEAN NOT NULL DEFAULT FALSE,
    descripcion_actividad TEXT NOT NULL,
    observaciones TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ats_estado ON public.ats(estado_id);
CREATE INDEX idx_ats_tipo ON public.ats(tipo_ats_id);
CREATE INDEX idx_ats_creado_por ON public.ats(creado_por_usuario_id);
CREATE INDEX idx_ats_fecha ON public.ats(fecha_elaboracion);

CREATE TABLE public.ats_apoyo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    apoyo_id INTEGER NOT NULL REFERENCES public.apoyo_catalogo(id),
    descripcion_otro TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ats_id, apoyo_id)
);

CREATE INDEX idx_ats_apoyo_ats ON public.ats_apoyo(ats_id);

CREATE TABLE public.ats_certificado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    certificado_id INTEGER NOT NULL REFERENCES public.certificado_catalogo(id),
    descripcion_otro TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ats_id, certificado_id)
);

CREATE INDEX idx_ats_certificado_ats ON public.ats_certificado(ats_id);

CREATE TABLE public.ats_peligro (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    peligro_id INTEGER NOT NULL REFERENCES public.peligro_catalogo(id),
    descripcion_otro TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ats_id, peligro_id)
);

CREATE INDEX idx_ats_peligro_ats ON public.ats_peligro(ats_id);

CREATE TABLE public.ats_paso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    numero_paso INTEGER NOT NULL CHECK (numero_paso > 0),
    descripcion_paso TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ats_id, numero_paso)
);

CREATE INDEX idx_ats_paso_ats ON public.ats_paso(ats_id);

CREATE TABLE public.ats_paso_peligro (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_paso_id INTEGER NOT NULL REFERENCES public.ats_paso(id) ON DELETE CASCADE,
    ats_peligro_id INTEGER NOT NULL REFERENCES public.ats_peligro(id) ON DELETE CASCADE,
    UNIQUE (ats_paso_id, ats_peligro_id)
);

CREATE INDEX idx_ats_paso_peligro_paso ON public.ats_paso_peligro(ats_paso_id);

CREATE TABLE public.ats_paso_peligro_control (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_paso_peligro_id INTEGER NOT NULL REFERENCES public.ats_paso_peligro(id) ON DELETE CASCADE,
    control_id INTEGER NOT NULL REFERENCES public.control_catalogo(id),
    control_aplicado TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ats_paso_peligro_id, control_id, control_aplicado)
);

CREATE INDEX idx_app_control_app ON public.ats_paso_peligro_control(ats_paso_peligro_id);
CREATE INDEX idx_app_control_control ON public.ats_paso_peligro_control(control_id);

CREATE TABLE public.ats_trabajador (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    numero_orden INTEGER NOT NULL CHECK (numero_orden > 0),

    -- Campos capturados/compatibilidad actual
    nombre_trabajador TEXT NOT NULL,
    numero_documento TEXT NOT NULL,
    cargo_trabajador TEXT,
    firma_base64 TEXT,

    -- Relación opcional al catálogo maestro y snapshot histórico
    trabajador_id INTEGER REFERENCES public.trabajador(id),
    nombre_snapshot TEXT,
    documento_snapshot TEXT,
    cargo_snapshot TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (ats_id, numero_orden)
);

CREATE INDEX idx_ats_trabajador_ats ON public.ats_trabajador(ats_id);
CREATE INDEX idx_ats_trabajador_trabajador ON public.ats_trabajador(trabajador_id);

CREATE TABLE public.ats_firma_final (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    firma_tipo_id INTEGER NOT NULL REFERENCES public.firma_tipo_catalogo(id),
    nombre_completo TEXT NOT NULL,
    cargo TEXT,
    firma_base64 TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ats_id, firma_tipo_id)
);

CREATE INDEX idx_ats_firma_final_ats ON public.ats_firma_final(ats_id);

CREATE TABLE public.ats_documento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ats_id INTEGER NOT NULL REFERENCES public.ats(id) ON DELETE CASCADE,
    tipo_documento TEXT NOT NULL,
    nombre_archivo TEXT NOT NULL,
    ruta_archivo TEXT NOT NULL,
    mime_type TEXT,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    generado_por_usuario_id INTEGER REFERENCES public.usuario(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ats_documento_ats ON public.ats_documento(ats_id);

-- ============================================================
-- Triggers updated_at
-- ============================================================

CREATE TRIGGER trg_usuario_updated_at
BEFORE UPDATE ON public.usuario
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_control_catalogo_updated_at
BEFORE UPDATE ON public.control_catalogo
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_trabajador_updated_at
BEFORE UPDATE ON public.trabajador
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ats_updated_at
BEFORE UPDATE ON public.ats
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ats_paso_updated_at
BEFORE UPDATE ON public.ats_paso
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ats_paso_peligro_control_updated_at
BEFORE UPDATE ON public.ats_paso_peligro_control
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ats_trabajador_updated_at
BEFORE UPDATE ON public.ats_trabajador
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ats_firma_final_updated_at
BEFORE UPDATE ON public.ats_firma_final
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- Datos catálogo migrados desde SQLite
-- ============================================================

-- Datos: rol (2 registros)

INSERT INTO public.rol (id, codigo, nombre, activo) VALUES
    (1, 'ADMIN', 'Administrador', TRUE),
    (2, 'SISO', 'Responsable SST', TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, activo = EXCLUDED.activo;

-- Datos: ats_estado (5 registros)

INSERT INTO public.ats_estado (id, codigo, nombre, orden, activo) VALUES
    (1, 'BORRADOR', 'Borrador', 1, TRUE),
    (2, 'EN_PROCESO', 'En proceso', 2, TRUE),
    (3, 'FINALIZADO', 'Finalizado', 3, TRUE),
    (4, 'DOCUMENTO_GENERADO', 'Documento generado', 4, TRUE),
    (5, 'ANULADO', 'Anulado', 5, TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, activo = EXCLUDED.activo;

-- Datos: ats_tipo (2 registros)

INSERT INTO public.ats_tipo (id, codigo, nombre, activo) VALUES
    (1, 'NUEVO', 'Nuevo', TRUE),
    (2, 'REVISION', 'Revisión', TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, activo = EXCLUDED.activo;

-- Datos: apoyo_catalogo (7 registros)

INSERT INTO public.apoyo_catalogo (id, codigo, nombre, permite_descripcion_libre, orden, activo) VALUES
    (1, 'PROGRAMA', 'Programa', FALSE, 1, TRUE),
    (2, 'PROCEDIMIENTO', 'Procedimiento', FALSE, 2, TRUE),
    (3, 'INSTRUCTIVO', 'Instructivo', FALSE, 3, TRUE),
    (4, 'ORDEN_SERVICIO', 'Orden de Servicio', FALSE, 4, TRUE),
    (5, 'PLAN_EMERGENCIA', 'Plan de Emergencia', FALSE, 5, TRUE),
    (6, 'PROC_MANTENIMIENTO', 'Procedimiento de Mantenimiento', FALSE, 6, TRUE),
    (7, 'OTROS', 'Otros', TRUE, 7, TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, permite_descripcion_libre = EXCLUDED.permite_descripcion_libre, orden = EXCLUDED.orden, activo = EXCLUDED.activo;

-- Datos: certificado_catalogo (5 registros)

INSERT INTO public.certificado_catalogo (id, codigo, nombre, permite_descripcion_libre, orden, activo) VALUES
    (1, 'ALTURAS', 'Alturas', FALSE, 1, TRUE),
    (2, 'ELECTRICOS', 'Eléctricos', FALSE, 2, TRUE),
    (3, 'ESPACIOS_CONFINADOS', 'Espacios Confinados', FALSE, 3, TRUE),
    (4, 'TRABAJOS_EN_CALIENTE', 'Trabajos en Caliente', FALSE, 4, TRUE),
    (5, 'OTROS', 'Otros', TRUE, 5, TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, permite_descripcion_libre = EXCLUDED.permite_descripcion_libre, orden = EXCLUDED.orden, activo = EXCLUDED.activo;

-- Datos: firma_tipo_catalogo (3 registros)

INSERT INTO public.firma_tipo_catalogo (id, codigo, nombre, orden, activo) VALUES
    (1, 'AUTORIZA', 'Autoriza Actividad SST', 1, TRUE),
    (2, 'SUPERVISA', 'Supervisa Actividad SST', 2, TRUE),
    (3, 'EJECUTA', 'Ejecuta Actividad', 3, TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, activo = EXCLUDED.activo;

-- Datos: peligro_catalogo (29 registros)

INSERT INTO public.peligro_catalogo (id, codigo, numero_visual, nombre, permite_descripcion_libre, orden, activo) VALUES
    (1, 'CAIDA_PERSONA_DISTINTO_NIVEL', 1, 'Caídas de Persona a Distinto Nivel', FALSE, 1, TRUE),
    (2, 'CAIDA_PERSONA_MISMO_NIVEL', 2, 'Caídas de Persona al Mismo Nivel', FALSE, 2, TRUE),
    (3, 'CAIDA_OBJETOS_DESPLOME', 3, 'Caída de Objetos por Desplome', FALSE, 3, TRUE),
    (4, 'CAIDA_OBJETOS_MANIPULACION', 4, 'Caídas de Objetos por Manipulación', FALSE, 4, TRUE),
    (5, 'CHOQUES_GOLPES_CONTRA', 5, 'Choques o Golpes con o Contra', FALSE, 5, TRUE),
    (6, 'CORTES_HERRAMIENTAS_OBJETOS', 6, 'Cortes por Herramientas u Objetos', FALSE, 6, TRUE),
    (7, 'PROYECCION_PARTICULAS', 7, 'Proyección de Partículas', FALSE, 7, TRUE),
    (8, 'ATRAPAMIENTO_APLASTAMIENTO', 8, 'Atrapamiento o Aplastamiento', FALSE, 8, TRUE),
    (9, 'CONTACTO_ENERGIAS_PELIGROSAS', 9, 'Contacto con Energías Peligrosas', FALSE, 9, TRUE),
    (10, 'TRABAJO_EN_CALIENTE', 10, 'Trabajo en Caliente', FALSE, 10, TRUE),
    (11, 'CAIDAS_DE_ALTURAS', 11, 'Caídas de Alturas', FALSE, 11, TRUE),
    (12, 'INGRESO_ESPACIO_CONFINADO', 12, 'Ingreso a Espacio Confinado', FALSE, 12, TRUE),
    (13, 'SOBREESFUERZOS', 13, 'Sobreesfuerzos', FALSE, 13, TRUE),
    (14, 'POSTURAS_PROLONGADAS', 14, 'Posturas Prolongadas o Incómodas', FALSE, 14, TRUE),
    (15, 'MANIPULACION_MANUAL_CARGAS', 15, 'Manipulación Manual de Cargas', FALSE, 15, TRUE),
    (16, 'MOVIMIENTOS_REPETITIVOS', 16, 'Movimientos Repetitivos', FALSE, 16, TRUE),
    (17, 'EXPOSICION_SUSTANCIAS_QUIMICAS', 17, 'Exposición o Contacto con Sustancias Químicas', FALSE, 17, TRUE),
    (18, 'EXPOSICION_GASES_VAPORES_POLVOS', 18, 'Exposición a Gases, Vapores o Polvos', FALSE, 18, TRUE),
    (19, 'CONTACTO_AGENTES_BIOLOGICOS', 19, 'Contactos con Agentes Biológicos', FALSE, 19, TRUE),
    (20, 'EXPOSICION_TEMPERATURAS_EXTREMAS', 20, 'Exposición a Temperaturas Extremas', FALSE, 20, TRUE),
    (21, 'RUIDO', 21, 'Ruido (Impacto, Continuo, Intermitente)', FALSE, 21, TRUE),
    (22, 'RADIACIONES', 22, 'Radiaciones (Ionizantes, No Ionizantes)', FALSE, 22, TRUE),
    (23, 'VIBRACIONES', 23, 'Vibraciones (Segmentos, Cuerpo Entero)', FALSE, 23, TRUE),
    (24, 'LUZ_EXCESO_DEFICIENTE', 24, 'Luz en Exceso o Deficiente', FALSE, 24, TRUE),
    (25, 'INCENDIO_EXPLOSION', 25, 'Incendio o Explosión', FALSE, 25, TRUE),
    (26, 'DERRAME_SUSTANCIAS', 26, 'Derrame de Sustancias', FALSE, 26, TRUE),
    (27, 'ACCIDENTES_TRANSITO', 27, 'Accidentes de Tránsito', FALSE, 27, TRUE),
    (28, 'ORDEN_PUBLICO', 28, 'Orden Público', FALSE, 28, TRUE),
    (29, 'OTRO_PELIGRO', 29, 'Otro Peligro', TRUE, 29, TRUE)
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, numero_visual = EXCLUDED.numero_visual, nombre = EXCLUDED.nombre, permite_descripcion_libre = EXCLUDED.permite_descripcion_libre, orden = EXCLUDED.orden, activo = EXCLUDED.activo;

-- Datos: control_catalogo (13 registros)

INSERT INTO public.control_catalogo (id, codigo, nombre, descripcion, tipo_control, permite_descripcion_libre, orden, activo, created_at, updated_at) VALUES
    (1, 'USO_EPP_BASICO', 'Uso obligatorio de EPP básico', 'Casco, gafas, guantes, botas y protección auditiva según actividad.', 'EPP', FALSE, 1, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (2, 'ARNES_LINEA_VIDA', 'Arnés y línea de vida certificados', 'Verificar puntos de anclaje, inspección preuso y certificación vigente.', 'EPP', FALSE, 2, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (3, 'DELIMITACION_AREA', 'Delimitación y señalización del área', 'Instalar conos, cinta, barreras y avisos preventivos.', 'Administrativo', FALSE, 3, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (4, 'BLOQUEO_ETIQUETADO', 'Bloqueo y etiquetado de energías', 'Aplicar LOTO, verificar ausencia de energía y liberar solo con autorización.', 'Ingeniería', FALSE, 4, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (5, 'PERMISO_TRABAJO', 'Permiso de trabajo aprobado', 'Validar permiso, alcance, responsables, vigencia y condiciones de seguridad.', 'Administrativo', FALSE, 5, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (6, 'INSPECCION_HERRAMIENTAS', 'Inspección preoperacional de herramientas', 'Retirar herramientas defectuosas y registrar hallazgos.', 'Administrativo', FALSE, 6, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (7, 'ORDEN_ASEO', 'Orden y aseo permanente', 'Mantener rutas libres, retirar obstáculos y controlar residuos.', 'Administrativo', FALSE, 7, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (8, 'VENTILACION_MONITOREO', 'Ventilación y monitoreo atmosférico', 'Verificar oxígeno, gases y ventilación antes y durante la tarea.', 'Ingeniería', FALSE, 8, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (9, 'EXTINTOR_VIGIA', 'Extintor y vigía de seguridad', 'Disponer extintor, vigía y control de fuentes de ignición.', 'Administrativo', FALSE, 9, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (10, 'PAUSAS_ACTIVAS', 'Pausas activas y manejo ergonómico', 'Aplicar técnicas de levantamiento, rotación de tareas y pausas activas.', 'Administrativo', FALSE, 10, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (11, 'CONTROL_CAIDA_OBJETOS', 'Control de caída de objetos', 'Usar amarre de herramientas, rodapiés y exclusión de área inferior.', 'Ingeniería', FALSE, 11, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (12, 'COMUNICACION_PERMANENTE', 'Comunicación permanente del equipo', 'Mantener radio o teléfono operativo y canal de comunicación definido.', 'Administrativo', FALSE, 12, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48'),
    (13, 'OTROS', 'Otros', 'Control no existente en catálogo; requiere descripción libre.', 'Otro', TRUE, 99, TRUE, '2026-05-11 18:29:48', '2026-05-11 18:29:48')
ON CONFLICT (id) DO UPDATE SET codigo = EXCLUDED.codigo, nombre = EXCLUDED.nombre, descripcion = EXCLUDED.descripcion, tipo_control = EXCLUDED.tipo_control, permite_descripcion_libre = EXCLUDED.permite_descripcion_libre, orden = EXCLUDED.orden, activo = EXCLUDED.activo, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;

-- ============================================================
-- Ajuste de secuencias después de inserts explícitos
-- ============================================================

SELECT setval(pg_get_serial_sequence('public.rol', 'id'), COALESCE((SELECT MAX(id) FROM public.rol), 1), (SELECT COUNT(*) > 0 FROM public.rol));
SELECT setval(pg_get_serial_sequence('public.usuario', 'id'), COALESCE((SELECT MAX(id) FROM public.usuario), 1), (SELECT COUNT(*) > 0 FROM public.usuario));
SELECT setval(pg_get_serial_sequence('public.ats_estado', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_estado), 1), (SELECT COUNT(*) > 0 FROM public.ats_estado));
SELECT setval(pg_get_serial_sequence('public.ats_tipo', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_tipo), 1), (SELECT COUNT(*) > 0 FROM public.ats_tipo));
SELECT setval(pg_get_serial_sequence('public.apoyo_catalogo', 'id'), COALESCE((SELECT MAX(id) FROM public.apoyo_catalogo), 1), (SELECT COUNT(*) > 0 FROM public.apoyo_catalogo));
SELECT setval(pg_get_serial_sequence('public.certificado_catalogo', 'id'), COALESCE((SELECT MAX(id) FROM public.certificado_catalogo), 1), (SELECT COUNT(*) > 0 FROM public.certificado_catalogo));
SELECT setval(pg_get_serial_sequence('public.firma_tipo_catalogo', 'id'), COALESCE((SELECT MAX(id) FROM public.firma_tipo_catalogo), 1), (SELECT COUNT(*) > 0 FROM public.firma_tipo_catalogo));
SELECT setval(pg_get_serial_sequence('public.peligro_catalogo', 'id'), COALESCE((SELECT MAX(id) FROM public.peligro_catalogo), 1), (SELECT COUNT(*) > 0 FROM public.peligro_catalogo));
SELECT setval(pg_get_serial_sequence('public.control_catalogo', 'id'), COALESCE((SELECT MAX(id) FROM public.control_catalogo), 1), (SELECT COUNT(*) > 0 FROM public.control_catalogo));
SELECT setval(pg_get_serial_sequence('public.trabajador', 'id'), COALESCE((SELECT MAX(id) FROM public.trabajador), 1), (SELECT COUNT(*) > 0 FROM public.trabajador));
SELECT setval(pg_get_serial_sequence('public.ats', 'id'), COALESCE((SELECT MAX(id) FROM public.ats), 1), (SELECT COUNT(*) > 0 FROM public.ats));
SELECT setval(pg_get_serial_sequence('public.ats_apoyo', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_apoyo), 1), (SELECT COUNT(*) > 0 FROM public.ats_apoyo));
SELECT setval(pg_get_serial_sequence('public.ats_certificado', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_certificado), 1), (SELECT COUNT(*) > 0 FROM public.ats_certificado));
SELECT setval(pg_get_serial_sequence('public.ats_peligro', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_peligro), 1), (SELECT COUNT(*) > 0 FROM public.ats_peligro));
SELECT setval(pg_get_serial_sequence('public.ats_paso', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_paso), 1), (SELECT COUNT(*) > 0 FROM public.ats_paso));
SELECT setval(pg_get_serial_sequence('public.ats_paso_peligro', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_paso_peligro), 1), (SELECT COUNT(*) > 0 FROM public.ats_paso_peligro));
SELECT setval(pg_get_serial_sequence('public.ats_paso_peligro_control', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_paso_peligro_control), 1), (SELECT COUNT(*) > 0 FROM public.ats_paso_peligro_control));
SELECT setval(pg_get_serial_sequence('public.ats_trabajador', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_trabajador), 1), (SELECT COUNT(*) > 0 FROM public.ats_trabajador));
SELECT setval(pg_get_serial_sequence('public.ats_firma_final', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_firma_final), 1), (SELECT COUNT(*) > 0 FROM public.ats_firma_final));
SELECT setval(pg_get_serial_sequence('public.ats_documento', 'id'), COALESCE((SELECT MAX(id) FROM public.ats_documento), 1), (SELECT COUNT(*) > 0 FROM public.ats_documento));

-- ============================================================
-- Vistas
-- ============================================================

CREATE OR REPLACE VIEW public.vw_ats_metrica_por_estado AS
SELECT
    e.id AS estado_id,
    e.codigo AS estado_codigo,
    e.nombre AS estado_nombre,
    COUNT(a.id) AS total_ats
FROM public.ats_estado e
LEFT JOIN public.ats a
       ON a.estado_id = e.id
GROUP BY e.id, e.codigo, e.nombre, e.orden
ORDER BY e.orden;

CREATE OR REPLACE VIEW public.vw_ats_metrica_por_peligro AS
SELECT
    p.id AS peligro_id,
    p.numero_visual,
    p.codigo AS peligro_codigo,
    p.nombre AS peligro_nombre,
    COUNT(ap.id) AS total_selecciones
FROM public.peligro_catalogo p
LEFT JOIN public.ats_peligro ap
       ON ap.peligro_id = p.id
GROUP BY p.id, p.numero_visual, p.codigo, p.nombre, p.orden
ORDER BY p.orden;

CREATE OR REPLACE VIEW public.vw_ats_paso_peligro_control AS
SELECT
    a.id AS ats_id,
    a.uuid AS ats_uuid,
    a.codigo_publico,
    p.id AS paso_id,
    p.numero_paso,
    p.descripcion_paso,
    app.id AS ats_paso_peligro_id,
    pc.id AS peligro_catalogo_id,
    pc.codigo AS peligro_codigo,
    pc.nombre AS peligro_nombre,
    c.id AS control_id,
    c.codigo AS control_codigo,
    c.nombre AS control_nombre,
    appc.control_aplicado
FROM public.ats_paso_peligro_control appc
JOIN public.ats_paso_peligro app ON app.id = appc.ats_paso_peligro_id
JOIN public.ats_paso p ON p.id = app.ats_paso_id
JOIN public.ats_peligro ap ON ap.id = app.ats_peligro_id
JOIN public.peligro_catalogo pc ON pc.id = ap.peligro_id
JOIN public.control_catalogo c ON c.id = appc.control_id
JOIN public.ats a ON a.id = p.ats_id;

CREATE OR REPLACE VIEW public.vw_ats_resumen AS
SELECT
    a.id,
    a.uuid,
    a.codigo_publico,
    a.fecha_elaboracion,
    a.ciudad,
    a.area_lugar,
    a.numero_ats,
    a.empresa_persona_ejecuta,
    a.duracion_actividad,
    a.actividad_alto_riesgo,
    a.descripcion_actividad,
    a.observaciones,
    e.codigo AS estado_codigo,
    e.nombre AS estado_nombre,
    t.codigo AS tipo_codigo,
    t.nombre AS tipo_nombre,
    u.username AS creado_por_username,
    u.nombre_completo AS creado_por_nombre,
    a.created_at,
    a.updated_at
FROM public.ats a
JOIN public.ats_estado e ON e.id = a.estado_id
JOIN public.ats_tipo t ON t.id = a.tipo_ats_id
JOIN public.usuario u ON u.id = a.creado_por_usuario_id;

CREATE OR REPLACE VIEW public.vw_ats_trabajador_snapshot AS
SELECT
    at.id AS ats_trabajador_id,
    a.id AS ats_id,
    a.uuid AS ats_uuid,
    a.codigo_publico,
    at.numero_orden,
    t.id AS trabajador_id,
    t.uuid AS trabajador_uuid,
    at.nombre_snapshot,
    at.documento_snapshot,
    at.cargo_snapshot,
    at.firma_base64,
    at.created_at
FROM public.ats_trabajador at
JOIN public.ats a ON a.id = at.ats_id
LEFT JOIN public.trabajador t ON t.id = at.trabajador_id;

-- ============================================================
-- Comentarios útiles para Supabase Auth
-- ============================================================

COMMENT ON TABLE public.usuario IS
'Perfil interno de la App ATS. auth_user_id referencia auth.users(id). Los roles de negocio se gestionan con public.rol.';
COMMENT ON COLUMN public.usuario.password_hash IS
'Campo de transición legado. Si se usa Supabase Auth, no guardar contraseñas aquí.';

-- ============================================================
-- RLS opcional
-- ============================================================
-- En una primera migración con App Web Reflex conectada por DATABASE_URL,
-- se recomienda validar primero CRUD sin RLS.
-- Cuando el acceso sea mediante Supabase API/cliente, habilitar RLS y políticas.
--
-- Ejemplo posterior:
-- ALTER TABLE public.ats ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;

COMMIT;
